formatter: markdown

sort:
  enabled: true
  by: required


output:
  file: "README.md"
  mode: replace
  # For the Pre-Commit to be happy with its newline
  template: "{{ .Content }}\n"


content: |-
  # Vault/OpenBao setup for GatePlane Services
  ![License: ElasticV2](https://img.shields.io/badge/ElasticV2-green?style=flat-square&label=license&cacheSeconds=3600&link=https%3A%2F%2Fwww.elastic.co%2Flicensing%2Felastic-license)

  ## How to use

  ### Team
  Call the module as below for the Team tier:
  ```hcl
  {{ include "examples/team/main.tf" }}
  ```

  ### Enterprise
  Additionally set the custom GatePlane WebUI domain for Enterprise tier:
  ```hcl
  {{ include "examples/enterprise/main.tf" }}
  ```

  The output will look like below:
  ```hcl
  {{ include "examples/output.txt" }}
  ```

  * The values under `net` must be submitted GatePlane Services if the Vault/OpenBao instance **can accept** Internet connections

  * The values under `no-net` must be submitted in case Vault/OpenBao instance is inaccessible from the Internet, located in an **internal network**, or is **air-gapped**.

  * [Team tier] The `web-ui` values must be set to the *Configuration* tab of the [GatePlane WebUI](https://app.gateplane.io) (Enterprise users do not need to do that).

  ## How to enable GatePlane Services

  After using this module, send the output field `full_output` to [`services@gateplane.io`](mailto:services@gateplane.io).

  The output of this module consists of Public keys and **non-sensitive information** only.

  ## What it does
  This Terraform module enables a Vault/OpenBao instance to use GatePlane Services

  * It creates an *OIDC Identity Provider* (IdP) supporting [*Proof Key for Code Exchange* (PKCE)](https://datatracker.ietf.org/doc/html/rfc7636) in Vault/OpenBao

  * Creates a Client App for the created IdP (named `gateplane`) and generates its keys

  * Creates a `messenger_options` scope providing to the GatePlane Services the relevant Vault/OpenBao Entity Metadata for the messenger application used (used by the Notification service)

  * Provides the JSON Web Key Sets (JWKS) and its URI, as well as the OIDC Audience (or client ID), needed to enable [Team or Enterprise tier](https://www.gateplane.io/#pricing) of GatePlane Services.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}


  ## License

  This project is licensed under the [Elastic License v2](https://www.elastic.co/licensing/elastic-license).

  This means:

  - ✅ You can use, fork, and modify it for **yourself** or **within your company**.
  - ✅ You can submit pull requests and redistribute modified versions (with the license attached).
  - ❌ You may **not** sell it, offer it as a paid product, or use it in a hosted service (e.g., SaaS).
  - ❌ You may **not** re-license it under a different license.

  In short: You can use and extend the code freely, privately or inside your business - just don’t build a business around it without our permission.
  [This FAQ by Elastic](https://www.elastic.co/licensing/elastic-license/faq) greatly summarizes things.

  See the [`./LICENSES/Elastic-2.0.txt`](./LICENSES/Elastic-2.0.txt) file for full details.
